name: scanner_personal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:


    sdk: flutter


  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  supabase_flutter: ^2.8.4
  audioplayers: ^4.1.0
  http: ^0.13.6
  google_fonts: ^4.0.4
  url_launcher: ^6.1.7
  image_picker: ^1.1.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: any
  shared_preferences: ^2.2.2
  bcrypt: ^1.1.3
  logger: ^1.0.0
  flutter_dotenv: ^5.2.1
  rxdart: ^0.28.0
  record: ^4.0.0 # Reemplazar audio_recorder
  just_audio: ^0.10.0 # Para reproducción
  universal_io: ^2.2.2
  flutter_js: ^0.7.2
  firebase_auth: ^5.5.2
  firebase_auth_web: ^5.14.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  assets:
    - .env
    - assets/logo.png

  uses-material-design: true
